### ISSUE TITLE
Cant have more blocks

### ISSUE THREAD

**Issue by SneakySquad** [AlessioDP/OreAnnouncer#12]
Hi i dont know what to do i did all the thing said in the messages and config but i cant get a number in the list please help...
Thanks
/Alexander
![Desktop 11-4-2019 7-05-03 PM-695](https://user-images.githubusercontent.com/42218683/68145445-16f54380-ff36-11e9-8c55-49daaaee1b34.png)
![Desktop 11-4-2019 7-05-13 PM-515](https://user-images.githubusercontent.com/42218683/68145451-19f03400-ff36-11e9-96a0-aae214705c63.png)

**Comment by AlessioDP** [comment]
Hello, when you edit a YAML file you have to be sure that you are correctly handling spaces/tabs.

In config.yml there are 2 spaces that should not be there at the line 184:
Example:
```
correct-list:
  a: true
  b: true
  c: true
wrong-list:
  a: true
    b: true
  c: true
```

PS. You should be able to see these errors in console log (not sure about that tho) ;)
