### ISSUE TITLE
DiscordSRV Integration no longer works

### ISSUE THREAD

**Issue by NFLD99** [AlessioDP/OreAnnouncer#96]
as per the title, DiscordSRV no longer sends a message when OA would normally post one, below is my configs
OA:
```
  discordsrv:
    enable: true
    message-format: text
    embed-avatars: true
    channels:
      user: oa
      admin: oa
```
DiscordSRV:
```
Channels: {"global": "812276288915767296","oa": "820411510491840533","staff-chat": "812277032678850600","auctionhouse": "826261474649047040","wispers": "833220932092035092"}
```

note: i get no console errors just the post from OA saying users has mined ore, but no discord message
